/**
 * Phase 33.1 — Scrolitha AI Assistant & productivity services.
 * ALL generation goes through ScrolithaAI.execute() only.
 * Drafts / suggestions only — never publish, send, apply, pay, or moderate.
 */
import { ScrolithaAI } from './execute';
import { loadAIFeatureFlags } from './config';
import { getAIConsent } from './consent';
import { inc, logAIEvent } from './observability';
import {
  createConversation,
  getConversation,
  appendMessage,
  listMessages
} from './conversations';
import {
  listPromptLibrary,
  getPromptLibraryItem,
  renderPromptTemplate
} from './promptLibrary';
import {
  suggestNotificationDigestSummary,
  suggestNotificationPriorities
} from './notificationHooks';
import type {
  ComposerMode,
  DraftKind,
  PrivacyLevel,
  RewriteMode,
  ScrolithaAIExecuteResult,
  SearchDomain
} from './types';

const DISCLOSURE_FOOTER =
  'Generated by Scrolitha AI as a draft/suggestion. Review before use. May be incorrect.';

export type AssistantSurfaceResult = {
  ok: boolean;
  blocked?: boolean;
  reason?: string;
  text?: string;
  disclosure?: ScrolithaAIExecuteResult['disclosure'] & { notice: string };
  conversationId?: string | null;
  messageId?: string | null;
  correlationId?: string;
  latencyMs?: number;
  mode?: string;
  domain?: string;
  suggestions?: string[];
  detectedLanguage?: string | null;
  draftOnly: true;
  autoPublished: false;
};

function fail(reason: string, extra: Partial<AssistantSurfaceResult> = {}): AssistantSurfaceResult {
  return {
    ok: false,
    blocked: true,
    reason,
    draftOnly: true,
    autoPublished: false,
    ...extra
  };
}

function okFromExecute(
  result: ScrolithaAIExecuteResult,
  extra: Partial<AssistantSurfaceResult> = {}
): AssistantSurfaceResult {
  if (!result.ok) {
    return fail(result.reason || 'AI_FAILED', {
      correlationId: result.correlationId,
      latencyMs: result.latencyMs,
      blocked: result.blocked
    });
  }
  return {
    ok: true,
    text: result.text,
    disclosure: {
      ...(result.disclosure || {
        generatedByAI: true,
        provider: 'MOCK',
        model: 'mock-foundation',
        promptVersion: '33.1',
        generatedAt: new Date().toISOString()
      }),
      notice: DISCLOSURE_FOOTER
    },
    correlationId: result.correlationId,
    latencyMs: result.latencyMs,
    draftOnly: true,
    autoPublished: false,
    ...extra
  };
}

async function assertSurface(
  userId: string,
  surfaceFlag: keyof Awaited<ReturnType<typeof loadAIFeatureFlags>>
): Promise<{ ok: true } | { ok: false; reason: string }> {
  const flags = await loadAIFeatureFlags();
  if (flags.killSwitch) return { ok: false, reason: 'AI_KILL_SWITCH' };
  if (!flags.masterEnabled) return { ok: false, reason: 'AI_MASTER_DISABLED' };
  if (!flags[surfaceFlag]) return { ok: false, reason: `SURFACE_FLAG_DISABLED:${String(surfaceFlag)}` };
  const consent = await getAIConsent(userId);
  if (!consent.aiFeaturesEnabled) return { ok: false, reason: 'CONSENT_AI_FEATURES_DISABLED' };
  if (!consent.aiSuggestionsAllowed) return { ok: false, reason: 'CONSENT_SUGGESTIONS_DISABLED' };
  return { ok: true };
}

/** Detect language heuristically (no external call) */
export function detectLanguage(text: string): string {
  const t = String(text || '');
  if (/[\u0600-\u06FF]/.test(t)) return 'ar';
  if (/[\u4e00-\u9fff]/.test(t)) return 'zh';
  if (/[\u3040-\u30ff]/.test(t)) return 'ja';
  if (/[\uac00-\ud7af]/.test(t)) return 'ko';
  if (/[\u0400-\u04FF]/.test(t)) return 'ru';
  if (/[àâäéèêëïîôùûüç]/i.test(t) && /\b(le|la|les|des|une|est)\b/i.test(t)) return 'fr';
  if (/[äöüß]/i.test(t) && /\b(der|die|das|und|ist)\b/i.test(t)) return 'de';
  if (/[ñáéíóúü]/i.test(t) && /\b(el|la|los|las|que|por)\b/i.test(t)) return 'es';
  return 'en';
}

/** Preserve @mentions, URLs, #hashtags across rewrites/translations by post-pass check */
export function preserveTokens(original: string, generated: string): string {
  const tokens = original.match(/(https?:\/\/[^\s]+|@[A-Za-z0-9_.]+|#[\p{L}\p{N}_]+)/gu) || [];
  let out = generated;
  for (const tok of tokens) {
    if (!out.includes(tok)) {
      // append preserved tokens if model dropped them
      out = `${out.trim()} ${tok}`.trim();
    }
  }
  return out;
}

export class ScrolithaAssistant {
  /** Chat / ask — creates or continues a conversation */
  static async chat(input: {
    userId: string;
    message: string;
    conversationId?: string | null;
    locale?: string;
    privacyLevel?: PrivacyLevel;
    correlationId?: string;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'assistantEnabled');
    if (gate.ok === false) return fail(gate.reason);

    const flags = await loadAIFeatureFlags();
    if (!flags.ASSISTANT_CHAT) return fail('CAPABILITY_FLAG_DISABLED:ASSISTANT_CHAT');

    const text = String(input.message || '').trim();
    if (!text || text.length > 12_000) return fail('INVALID_INPUT');

    let conversationId = input.conversationId || null;
    if (conversationId) {
      const c = await getConversation(input.userId, conversationId);
      if (!c) return fail('CONVERSATION_NOT_FOUND');
    } else {
      const c = await createConversation(input.userId);
      conversationId = c.id;
      inc('assistantSessions');
    }

    await appendMessage({
      userId: input.userId,
      conversationId,
      role: 'user',
      content: text,
      capability: 'ASSISTANT_CHAT'
    });

    // Limited history context (previews only in execute input)
    const history = await listMessages(input.userId, conversationId, 8);
    const historyBlock = history
      .slice(0, -1)
      .map((m) => `${m.role}: ${m.contentPreview}`)
      .join('\n')
      .slice(0, 2000);

    const result = await ScrolithaAI.execute({
      capability: 'ASSISTANT_CHAT',
      userId: input.userId,
      input: historyBlock ? `Prior context:\n${historyBlock}\n\nUser:\n${text}` : text,
      locale: input.locale || 'en',
      policy: {
        privacyLevel: input.privacyLevel || 'PERSONAL',
        preferInternalProvider: true,
        allowCache: false,
        maxTokens: 1200
      },
      correlationId: input.correlationId,
      metadata: { surface: 'assistant_chat', conversationId }
    });

    inc('assistantMessages');
    const surface = okFromExecute(result, { conversationId });
    if (surface.ok && surface.text) {
      const msg = await appendMessage({
        userId: input.userId,
        conversationId,
        role: 'assistant',
        content: surface.text,
        disclosure: surface.disclosure || null,
        capability: 'ASSISTANT_CHAT',
        correlationId: result.correlationId
      });
      surface.messageId = msg?.id || null;
    }
    return surface;
  }

  static async rewrite(input: {
    userId: string;
    text: string;
    mode: RewriteMode;
    locale?: string;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'rewriteEnabled');
    if (gate.ok === false) return fail(gate.reason);
    const flags = await loadAIFeatureFlags();
    if (!flags.TEXT_REWRITING) return fail('CAPABILITY_FLAG_DISABLED:TEXT_REWRITING');

    const text = String(input.text || '').trim();
    if (!text) return fail('INVALID_INPUT');

    const mode = input.mode || 'rewrite';
    const instruction = {
      rewrite: 'Rewrite clearly while preserving meaning.',
      summarize: 'Summarize concisely.',
      bullet_points: 'Convert into bullet points.',
      simplify: 'Simplify language for a general audience.',
      professional: 'Rewrite in a professional tone.',
      executive_summary: 'Write a short executive summary.',
      social: 'Rewrite for social media (engaging, concise).',
      seo: 'Rewrite for SEO clarity with natural keywords.'
    }[mode];

    const capability = mode === 'summarize' || mode === 'executive_summary' ? 'TEXT_SUMMARIZATION' : 'TEXT_REWRITING';
    if (capability === 'TEXT_SUMMARIZATION' && !flags.TEXT_SUMMARIZATION) {
      return fail('CAPABILITY_FLAG_DISABLED:TEXT_SUMMARIZATION');
    }

    const result = await ScrolithaAI.execute({
      capability,
      userId: input.userId,
      input: `${instruction}\n\nText:\n${text}`,
      locale: input.locale || 'en',
      policy: { privacyLevel: 'PERSONAL', preferInternalProvider: true, allowCache: false },
      metadata: { surface: 'rewrite', mode }
    });
    if (mode === 'summarize' || mode === 'executive_summary') inc('summariesGenerated');
    else inc('rewriteRequests');
    const surface = okFromExecute(result, { mode });
    if (surface.ok && surface.text) {
      surface.text = preserveTokens(text, surface.text);
    }
    return surface;
  }

  static async composer(input: {
    userId: string;
    text: string;
    mode: ComposerMode;
    surface?: string;
    locale?: string;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'composerEnabled');
    if (gate.ok === false) return fail(gate.reason);
    const flags = await loadAIFeatureFlags();
    if (!flags.COMPOSER_ASSIST) return fail('CAPABILITY_FLAG_DISABLED:COMPOSER_ASSIST');

    const text = String(input.text || '').trim();
    if (!text) return fail('INVALID_INPUT');

    const modeHelp: Record<ComposerMode, string> = {
      improve: 'Improve clarity and flow.',
      expand: 'Expand with useful detail (still concise).',
      shorten: 'Shorten while keeping key meaning.',
      professional: 'Professional tone.',
      friendly: 'Friendly tone.',
      formal: 'Formal tone.',
      casual: 'Casual tone.',
      grammar: 'Fix grammar only.',
      spelling: 'Fix spelling only.',
      keywords: 'Suggest concise, role-relevant keywords and skills. Return a comma-separated list only.',
      hashtags: 'Suggest relevant hashtags (append as a short list).',
      emoji: 'Suggest tasteful emoji placement (do not overuse).'
    };

    const result = await ScrolithaAI.execute({
      capability: 'COMPOSER_ASSIST',
      userId: input.userId,
      input: `Mode: ${input.mode}\nInstruction: ${modeHelp[input.mode] || 'Improve writing.'}\nSurface: ${input.surface || 'generic'}\n\nText:\n${text}`,
      locale: input.locale || 'en',
      policy: { privacyLevel: 'PERSONAL', preferInternalProvider: true, allowCache: false },
      metadata: { surface: 'composer', mode: input.mode, uiSurface: input.surface }
    });
    inc('composerAssists');
    const surface = okFromExecute(result, { mode: input.mode });
    if (surface.ok && surface.text) surface.text = preserveTokens(text, surface.text);
    return surface;
  }

  static async translate(input: {
    userId: string;
    text: string;
    targetLocale: string;
    sourceLocale?: string | null;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'translationEnabled');
    if (gate.ok === false) return fail(gate.reason);
    const flags = await loadAIFeatureFlags();
    if (!flags.TEXT_TRANSLATION) return fail('CAPABILITY_FLAG_DISABLED:TEXT_TRANSLATION');

    const text = String(input.text || '').trim();
    if (!text) return fail('INVALID_INPUT');
    const target = String(input.targetLocale || 'en').slice(0, 16);
    const detected = input.sourceLocale || detectLanguage(text);

    const result = await ScrolithaAI.execute({
      capability: 'TEXT_TRANSLATION',
      userId: input.userId,
      input: text,
      locale: target,
      policy: { privacyLevel: 'PERSONAL', preferInternalProvider: true, allowCache: false },
      metadata: { surface: 'translation', source: detected, target }
    });
    inc('translationRequests');
    const surface = okFromExecute(result, { detectedLanguage: detected, mode: `translate:${target}` });
    if (surface.ok && surface.text) surface.text = preserveTokens(text, surface.text);
    return surface;
  }

  static async draft(input: {
    userId: string;
    kind: DraftKind;
    topic: string;
    extra?: string;
    locale?: string;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'assistantEnabled');
    if (gate.ok === false) return fail(gate.reason);
    const flags = await loadAIFeatureFlags();
    if (!flags.DRAFT_COMPOSITION) return fail('CAPABILITY_FLAG_DISABLED:DRAFT_COMPOSITION');

    // Domain-specific surface flags
    const jobsKinds = new Set(['cover_letter', 'resume_summary', 'job_response', 'job_description']);
    const marketKinds = new Set(['marketplace_listing', 'product_title', 'product_description', 'seo_keywords']);
    const bizKinds = new Set(['business_announcement', 'marketing_post', 'promotion']);
    if (jobsKinds.has(input.kind) && !flags.jobsDraftingEnabled) {
      return fail('SURFACE_FLAG_DISABLED:jobsDraftingEnabled');
    }
    if (marketKinds.has(input.kind) && !flags.marketplaceDraftingEnabled) {
      return fail('SURFACE_FLAG_DISABLED:marketplaceDraftingEnabled');
    }
    if (bizKinds.has(input.kind) && !flags.businessPageDraftingEnabled) {
      return fail('SURFACE_FLAG_DISABLED:businessPageDraftingEnabled');
    }

    const topic = String(input.topic || '').trim();
    if (!topic) return fail('INVALID_INPUT');

    const result = await ScrolithaAI.execute({
      capability: 'DRAFT_COMPOSITION',
      userId: input.userId,
      input: `Draft kind: ${input.kind}\nTopic:\n${topic}\n${input.extra ? `Extra:\n${input.extra}` : ''}\n\nReturn DRAFT ONLY. Never claim you published or submitted.`,
      locale: input.locale || 'en',
      policy: { privacyLevel: 'PERSONAL', preferInternalProvider: true, allowCache: false },
      metadata: { surface: 'draft', kind: input.kind }
    });
    inc('draftsGenerated');
    return okFromExecute(result, { mode: input.kind });
  }

  static async searchSuggestions(input: {
    userId: string;
    domain: SearchDomain;
    query: string;
    locale?: string;
  }): Promise<AssistantSurfaceResult> {
    const gate = await assertSurface(input.userId, 'searchSuggestionsEnabled');
    if (gate.ok === false) return fail(gate.reason);
    const flags = await loadAIFeatureFlags();
    if (!flags.SEARCH_QUERY_SUGGESTION) return fail('CAPABILITY_FLAG_DISABLED:SEARCH_QUERY_SUGGESTION');

    const query = String(input.query || '').trim();
    if (!query) return fail('INVALID_INPUT');

    const result = await ScrolithaAI.execute({
      capability: 'SEARCH_QUERY_SUGGESTION',
      userId: input.userId,
      input: `Domain: ${input.domain}\nIntent: ${query}`,
      locale: input.locale || 'en',
      policy: { privacyLevel: 'PUBLIC', preferInternalProvider: true, allowCache: true },
      metadata: { surface: 'search_suggestions', domain: input.domain }
    });
    inc('searchSuggestions');
    const surface = okFromExecute(result, { domain: input.domain });
    if (surface.ok && surface.text) {
      surface.suggestions = surface.text
        .split(/\n+/)
        .map((l) => l.replace(/^[-*\d.)\s]+/, '').trim())
        .filter(Boolean)
        .slice(0, 8);
    }
    return surface;
  }

  static async usePromptLibrary(input: {
    userId: string;
    promptId: string;
    topic: string;
    locale?: string;
    conversationId?: string | null;
  }): Promise<AssistantSurfaceResult> {
    const flags = await loadAIFeatureFlags();
    if (!flags.promptLibraryEnabled) return fail('SURFACE_FLAG_DISABLED:promptLibraryEnabled');
    const item = getPromptLibraryItem(input.promptId);
    if (!item) return fail('PROMPT_NOT_FOUND');
    inc('promptLibraryUses');
    const userMessage = renderPromptTemplate(item, { topic: input.topic || '' });
    if (item.draftKind) {
      return this.draft({
        userId: input.userId,
        kind: item.draftKind as DraftKind,
        topic: input.topic,
        locale: input.locale
      });
    }
    return this.chat({
      userId: input.userId,
      message: userMessage,
      conversationId: input.conversationId,
      locale: input.locale
    });
  }

  /** Notification explain/summarize/group/priority — never overrides Phase 32 priority */
  static async notificationAssist(input: {
    userId: string;
    action: 'explain' | 'summarize' | 'group' | 'prioritize';
    items: Array<{ id: string; title?: string; body?: string; category?: string; priority?: string }>;
    locale?: string;
  }): Promise<AssistantSurfaceResult & { suggestion?: unknown }> {
    const gate = await assertSurface(input.userId, 'assistantEnabled');
    if (gate.ok === false) return fail(gate.reason);

    if (input.action === 'summarize') {
      const r = await suggestNotificationDigestSummary({
        userId: input.userId,
        items: input.items,
        locale: input.locale
      });
      if (!r.usedAI) return fail(r.reason || 'NOTIFICATION_AI_UNAVAILABLE');
      return {
        ok: true,
        text: r.suggestion?.summary || '',
        suggestion: r.suggestion,
        draftOnly: true,
        autoPublished: false,
        disclosure: {
          generatedByAI: true,
          provider: 'gateway',
          model: 'notification-hook',
          promptVersion: '33.1',
          generatedAt: new Date().toISOString(),
          notice: 'Suggestion only. Deterministic notification priority remains authoritative.'
        }
      };
    }

    if (input.action === 'prioritize') {
      const r = await suggestNotificationPriorities({
        userId: input.userId,
        items: input.items,
        locale: input.locale
      });
      if (!r.usedAI) return fail(r.reason || 'NOTIFICATION_AI_UNAVAILABLE');
      return {
        ok: true,
        text: JSON.stringify(r.suggestion),
        suggestion: r.suggestion,
        draftOnly: true,
        autoPublished: false,
        disclosure: {
          generatedByAI: true,
          provider: 'gateway',
          model: 'notification-hook',
          promptVersion: '33.1',
          generatedAt: new Date().toISOString(),
          notice: 'Priority suggestions do not override Phase 32 security/emergency policy.'
        }
      };
    }

    // explain / group via assistant chat capability with constrained prompt
    const list = input.items
      .slice(0, 30)
      .map((i) => `- [${i.id}] (${i.priority || 'normal'}) ${i.title || ''}: ${String(i.body || '').slice(0, 120)}`)
      .join('\n');
    const result = await ScrolithaAI.execute({
      capability: 'ASSISTANT_CHAT',
      userId: input.userId,
      input:
        input.action === 'group'
          ? `Suggest logical groups for these notifications (suggestion only):\n${list}`
          : `Explain these notifications briefly for the user (suggestion only):\n${list}`,
      locale: input.locale || 'en',
      policy: { privacyLevel: 'PERSONAL', preferInternalProvider: true, allowCache: false },
      metadata: { surface: 'notification_assist', action: input.action }
    });
    return okFromExecute(result, { mode: `notification_${input.action}` });
  }

  static listPrompts = listPromptLibrary;
}

export default ScrolithaAssistant;
