/**
 * Phase 33.0 — Schema-validated structured outputs (bounded, versioned).
 */

export type NotificationSummary = {
  summary: string;
  keyItems: Array<{
    notificationId: string;
    reason: string;
    priority: 'CRITICAL' | 'HIGH' | 'NORMAL' | 'LOW';
  }>;
  generatedAt: string;
  modelDisclosure: string;
};

export type NotificationPrioritySuggestions = {
  suggestions: Array<{
    notificationId?: string;
    priority: 'CRITICAL' | 'HIGH' | 'NORMAL' | 'LOW';
    reason: string;
  }>;
  generatedAt: string;
};

function extractJson(raw: string): unknown {
  const text = String(raw || '').trim();
  if (!text) return {};
  try {
    return JSON.parse(text);
  } catch {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start >= 0 && end > start) {
      try {
        return JSON.parse(text.slice(start, end + 1));
      } catch {
        return {};
      }
    }
    return {};
  }
}

const PRIORITIES = new Set(['CRITICAL', 'HIGH', 'NORMAL', 'LOW']);

export function parseNotificationSummary(raw: string): NotificationSummary {
  const obj = extractJson(raw) as any;
  const keyItems = Array.isArray(obj.keyItems) ? obj.keyItems.slice(0, 50) : [];
  return {
    summary: String(obj.summary || raw || '').slice(0, 2000),
    keyItems: keyItems.map((k: any) => ({
      notificationId: String(k.notificationId || '').slice(0, 128),
      reason: String(k.reason || '').slice(0, 500),
      priority: PRIORITIES.has(String(k.priority || '').toUpperCase())
        ? (String(k.priority).toUpperCase() as NotificationSummary['keyItems'][0]['priority'])
        : 'NORMAL'
    })),
    generatedAt: String(obj.generatedAt || new Date().toISOString()),
    modelDisclosure: String(obj.modelDisclosure || 'Generated by Scrolitha AI (suggestion only)')
  };
}

export function validateNotificationSummary(v: NotificationSummary): boolean {
  return Boolean(v && typeof v.summary === 'string' && Array.isArray(v.keyItems));
}

export function parseNotificationPriority(raw: string): NotificationPrioritySuggestions {
  const obj = extractJson(raw) as any;
  const suggestions = Array.isArray(obj.suggestions) ? obj.suggestions.slice(0, 100) : [];
  return {
    suggestions: suggestions.map((s: any) => ({
      notificationId: s.notificationId ? String(s.notificationId).slice(0, 128) : undefined,
      priority: PRIORITIES.has(String(s.priority || '').toUpperCase())
        ? (String(s.priority).toUpperCase() as any)
        : 'NORMAL',
      reason: String(s.reason || '').slice(0, 500)
    })),
    generatedAt: String(obj.generatedAt || new Date().toISOString())
  };
}

export function validateNotificationPriority(v: NotificationPrioritySuggestions): boolean {
  return Boolean(v && Array.isArray(v.suggestions));
}

export function parseGenericExtraction(raw: string): Record<string, unknown> {
  const obj = extractJson(raw);
  if (obj && typeof obj === 'object' && !Array.isArray(obj)) return obj as Record<string, unknown>;
  return { value: String(raw || '').slice(0, 2000) };
}

export function validateGenericExtraction(v: Record<string, unknown>): boolean {
  return Boolean(v && typeof v === 'object');
}
