ALTER TABLE "files"
ADD COLUMN IF NOT EXISTS "storage_provider" TEXT NOT NULL DEFAULT 'local',
ADD COLUMN IF NOT EXISTS "thumbnail_url" TEXT,
ADD COLUMN IF NOT EXISTS "width" INTEGER,
ADD COLUMN IF NOT EXISTS "height" INTEGER,
ADD COLUMN IF NOT EXISTS "duration" DOUBLE PRECISION;
