steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/scrolitha-core/Dockerfile
      - --build-arg
      - SCROLITHA_OLLAMA_MODEL=qwen3:14b
      - -t
      - asia-southeast1-docker.pkg.dev/scrolith-500821/scrolith/scrolitha-core:prod
      - .
images:
  - asia-southeast1-docker.pkg.dev/scrolith-500821/scrolith/scrolitha-core:prod
