steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        Dockerfile.storyfix.runtime,
        --no-cache,
        -t,
        asia-southeast1-docker.pkg.dev/scrolith-500821/scrolith/scrolith-backend:p23,
        --label,
        git_commit=951080ed,
        --label,
        phase=23A,
        .
      ]
images:
  - asia-southeast1-docker.pkg.dev/scrolith-500821/scrolith/scrolith-backend:p23
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: 2400s
