FROM node:20-alpine AS runtime

WORKDIR /app/geezle-backend

COPY package*.json ./
RUN npm ci --include=dev \
  && npm cache clean --force

COPY src ./src
COPY prisma ./prisma
COPY scripts ./scripts
COPY tsconfig*.json ./

RUN npm run prisma:generate
RUN npm run build:prod

ENV NODE_ENV=production

EXPOSE 5000

CMD ["sh", "-c", "npm run migrate:apply && node dist/server.js"]
