import React, { useEffect, useState } from 'react';
import api from '../../services/api';
import { PauseCircle, PlayCircle, UsersRound, RefreshCw, ShieldCheck } from 'lucide-react';

const unwrap = (r: any) => r?.data?.data ?? r?.data ?? r;
const sourceTypes = ['ads', 'gig_commissions', 'paid_plans'];

const FoundingPartners: React.FC = () => {
  const [program, setProgram] = useState<any>(null);
  const [partners, setPartners] = useState<any[]>([]);
  const [periods, setPeriods] = useState<any[]>([]);
  const [year, setYear] = useState(new Date().getFullYear() - 1);
  const [sources, setSources] = useState<Record<string, string>>({ ads: '', gig_commissions: '', paid_plans: '' });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');

  const load = async () => {
    setLoading(true); setError('');
    try {
      const [p, rows, profitPeriods] = await Promise.all([api.get('/admin/founding-partners/program'), api.get('/admin/founding-partners/partners?limit=50'), api.get('/admin/founding-partners/profit-periods')]);
      setProgram(unwrap(p)); setPartners(unwrap(rows)?.items || []); setPeriods(unwrap(profitPeriods) || []);
    } catch (e: any) { setError(e?.response?.data?.error || 'Unable to load Founding Partners.'); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  const run = async (action: () => Promise<any>) => { setBusy(true); setError(''); try { await action(); await load(); } catch (e: any) { setError(e?.response?.data?.error || 'The operation could not be completed.'); } finally { setBusy(false); } };
  const setStatus = (status: string) => run(() => api.post('/admin/founding-partners/program/status', { status }));
  const togglePartner = (row: any) => run(() => api.post(`/admin/founding-partners/partners/${row.id}/${row.status === 'ACTIVE' ? 'deactivate' : 'reactivate'}`));
  const savePeriod = () => run(() => api.post('/admin/founding-partners/profit-periods', { year, sources: sourceTypes.map((sourceType) => ({ sourceType, clearedAmount: Number(sources[sourceType] || 0), adjustments: 0 })) }));

  if (loading) return <div className="rounded-xl border bg-white p-6 text-sm text-slate-500">Loading Founding Partners...</div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-indigo-600">Partnership / Profit Participation</p><h1 className="text-2xl font-semibold text-slate-900">Founding Partners</h1><p className="text-sm text-slate-500">Manage enrollment, cleared-profit periods, approvals, and auditable wallet distributions.</p></div><div className="flex gap-2"><button disabled={busy} onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button>{program && <button disabled={busy} onClick={() => void setStatus(program.status === 'ACTIVE' ? 'PAUSED' : 'ACTIVE')} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium">{program.status === 'ACTIVE' ? <PauseCircle className="h-4 w-4" /> : <PlayCircle className="h-4 w-4" />}{program.status === 'ACTIVE' ? 'Pause enrollment' : 'Activate enrollment'}</button>}</div></div>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {program && <div className="grid gap-4 sm:grid-cols-4"><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Status</p><p className="mt-1 font-semibold">{program.status}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Capacity</p><p className="mt-1 font-semibold">{program.enrolledCount.toLocaleString()} / {program.capacity.toLocaleString()}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Pool share / term</p><p className="mt-1 font-semibold">{program.profitSharePercent}% / {program.termYears} years</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Enrollment fee</p><p className="mt-1 font-semibold">{program.currency} {program.enrollmentFee}</p></div></div>}
    <section className="rounded-xl border bg-white p-5"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-indigo-600" /><div><h2 className="font-semibold">Cleared-profit period</h2><p className="text-xs text-slate-500">Only closed and separately approved periods may create a distribution run.</p></div></div><div className="grid gap-3 md:grid-cols-4"><label className="text-sm">Year<input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>{sourceTypes.map((sourceType) => <label key={sourceType} className="text-sm capitalize">{sourceType.replace('_', ' ')}<input type="number" min="0" step="0.01" value={sources[sourceType]} onChange={(e) => setSources((current) => ({ ...current, [sourceType]: e.target.value }))} className="mt-1 w-full rounded-lg border px-3 py-2" placeholder="0.00" /></label>)}</div><button disabled={busy} onClick={() => void savePeriod()} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Save profit sources</button><div className="mt-5 space-y-2">{periods.map((period) => <div key={period.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3 text-sm"><div><span className="font-medium">{period.periodYear}</span><span className="ml-3 text-slate-500">{period.status} · pool {period.partnerPool?.toString?.() || '0.00'}</span></div><div className="flex flex-wrap gap-2">{period.status === 'OPEN' && <button disabled={busy} onClick={() => void run(() => api.post(`/admin/founding-partners/profit-periods/${period.id}/close`))} className="rounded border px-3 py-1.5 text-xs">Close</button>}{period.status === 'CLOSED' && <button disabled={busy} onClick={() => void run(() => api.post(`/admin/founding-partners/profit-periods/${period.id}/approve`))} className="rounded border px-3 py-1.5 text-xs">Approve period</button>}{period.status === 'APPROVED' && !period.distributionRun && <button disabled={busy} onClick={() => void run(() => api.post(`/admin/founding-partners/profit-periods/${period.id}/distribution-run`))} className="rounded border px-3 py-1.5 text-xs">Create run</button>}{period.distributionRun?.status === 'PENDING_APPROVAL' && <button disabled={busy} onClick={() => void run(() => api.post(`/admin/founding-partners/distribution-runs/${period.distributionRun.id}/approve`))} className="rounded border px-3 py-1.5 text-xs">Approve run</button>}{period.distributionRun?.status === 'APPROVED' && <button disabled={busy} onClick={() => void run(() => api.post(`/admin/founding-partners/distribution-runs/${period.distributionRun.id}/execute`))} className="rounded bg-indigo-600 px-3 py-1.5 text-xs text-white">Execute run</button>}</div></div>)}</div></section>
    <div className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center gap-2 border-b p-4"><UsersRound className="h-5 w-5 text-indigo-600" /><h2 className="font-semibold">Enrolled partners</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Partner</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{partners.map((row) => <tr key={row.id} className="border-t"><td className="px-4 py-3"><p className="font-medium">{row.fullName}</p><p className="text-xs text-slate-500">{row.user?.email}</p></td><td className="px-4 py-3">{row.city}, {row.country}</td><td className="px-4 py-3">{row.enrollmentPayment?.status || '—'}</td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3"><button disabled={busy} onClick={() => void togglePartner(row)} className="rounded-lg border px-3 py-1.5 text-xs">{row.status === 'ACTIVE' ? 'Deactivate' : 'Reactivate'}</button></td></tr>)}</tbody></table>{partners.length === 0 && <p className="p-6 text-sm text-slate-500">No partners enrolled yet.</p>}</div></div>
  </div>;
};

export default FoundingPartners;
