export const SCROLITHA_USERNAME = 'scrolitha';
export const SCROLITHA_DISPLAY_NAME = 'Scrolitha';
export const SCROLITHA_SYSTEM_LABEL = 'AI assistant';
export const SCROLITHA_DISCLOSURE =
  'This response was generated by Scrolitha, Scrolith’s AI assistant. Verify important claims independently.';

export const isScrolithaUsername = (username?: string | null): boolean =>
  String(username || '')
    .trim()
    .toLowerCase()
    .replace(/^@/, '') === SCROLITHA_USERNAME;

export const isScrolithaComment = (comment: {
  isScrolitha?: boolean;
  isAiGenerated?: boolean;
  userUsername?: string | null;
  author?: { username?: string | null; isScrolitha?: boolean } | null;
  systemLabel?: string | null;
}): boolean => {
  if (comment?.isScrolitha || comment?.isAiGenerated || comment?.author?.isScrolitha) return true;
  if (isScrolithaUsername(comment?.userUsername) || isScrolithaUsername(comment?.author?.username)) return true;
  return false;
};

export const mentionsScrolitha = (content?: string | null): boolean => {
  const text = String(content || '');
  return /(^|[^@\w])@scrolitha\b/i.test(text);
};

const DISMISS_PREFIX = 'scrolitha:proactive:dismissed:';
const SESSION_SUGGEST_PREFIX = 'scrolitha:proactive:session:';
const MAX_SESSION_SUGGESTS = 8;

export const isProactiveSuggestionDismissed = (postId: string): boolean => {
  try {
    return window.localStorage.getItem(`${DISMISS_PREFIX}${postId}`) === '1';
  } catch {
    return false;
  }
};

export const dismissProactiveSuggestion = (postId: string) => {
  try {
    window.localStorage.setItem(`${DISMISS_PREFIX}${postId}`, '1');
  } catch {
    // ignore storage failures
  }
};

/** Session-level anti-spam: cap how many Ask chips can auto-surface this tab session. */
export const canShowSessionSuggestion = (): boolean => {
  try {
    const raw = window.sessionStorage.getItem(SESSION_SUGGEST_PREFIX);
    const count = Number(raw || 0);
    return !Number.isFinite(count) || count < MAX_SESSION_SUGGESTS;
  } catch {
    return true;
  }
};

export const recordSessionSuggestionShown = () => {
  try {
    const raw = window.sessionStorage.getItem(SESSION_SUGGEST_PREFIX);
    const count = Number(raw || 0);
    window.sessionStorage.setItem(SESSION_SUGGEST_PREFIX, String((Number.isFinite(count) ? count : 0) + 1));
  } catch {
    // ignore
  }
};

/** Multi-tab dedupe of pending Scrolitha request state. */
export const broadcastScrolithaPending = (payload: {
  postId: string;
  commentId: string;
  status: 'reviewing' | 'failed' | 'completed';
}) => {
  try {
    if (typeof BroadcastChannel === 'undefined') return;
    const channel = new BroadcastChannel('scrolitha-contextual');
    channel.postMessage({ type: 'pending', ...payload, at: Date.now() });
    channel.close();
  } catch {
    // ignore
  }
};

export const subscribeScrolithaPending = (
  handler: (payload: { postId: string; commentId: string; status: string }) => void
) => {
  try {
    if (typeof BroadcastChannel === 'undefined') return () => undefined;
    const channel = new BroadcastChannel('scrolitha-contextual');
    const onMessage = (event: MessageEvent) => {
      const data = event?.data;
      if (!data || data.type !== 'pending') return;
      handler({
        postId: String(data.postId || ''),
        commentId: String(data.commentId || ''),
        status: String(data.status || '')
      });
    };
    channel.addEventListener('message', onMessage);
    return () => {
      channel.removeEventListener('message', onMessage);
      channel.close();
    };
  } catch {
    return () => undefined;
  }
};
