import prisma from '../../utils/prismaClient';

/**
 * Stable platform identity for Scrolitha AI replies in comment threads.
 * Uses existing User model only — no schema migration.
 */
export const SCROLITHA_PLATFORM_USERNAME = 'scrolitha';
export const SCROLITHA_PLATFORM_DISPLAY_NAME = 'Scrolitha';
export const SCROLITHA_PLATFORM_EMAIL = 'scrolitha@system.scrolith.internal';
export const SCROLITHA_SYSTEM_LABEL = 'AI assistant';
export const SCROLITHA_DISCLOSURE =
  'This response was generated by Scrolitha, Scrolith’s AI assistant. Verify important claims independently.';

export type ScrolithaPlatformUser = {
  id: string;
  username: string;
  name: string;
  avatar: string | null;
  isVerified: boolean;
  isActive: boolean;
  role: string;
  isScrolitha: true;
  systemLabel: string;
  disclosure: string;
};

const IDENTITY_CACHE_TTL_MS = 5 * 60_000;
let identityCache: { expiresAt: number; value: ScrolithaPlatformUser } | null = null;

const toPublicIdentity = (user: {
  id: string;
  username: string | null;
  name: string | null;
  avatar: string | null;
  isVerified: boolean;
  isActive: boolean;
  role: string;
}): ScrolithaPlatformUser => ({
  id: user.id,
  username: String(user.username || SCROLITHA_PLATFORM_USERNAME).toLowerCase(),
  name: user.name || SCROLITHA_PLATFORM_DISPLAY_NAME,
  avatar: user.avatar || null,
  isVerified: Boolean(user.isVerified),
  isActive: user.isActive !== false,
  role: String(user.role || 'USER'),
  isScrolitha: true,
  systemLabel: SCROLITHA_SYSTEM_LABEL,
  disclosure: SCROLITHA_DISCLOSURE
});

/**
 * Find or create the reserved Scrolitha platform user.
 * Protected identity: fixed username, verified badge, inactive for normal login paths.
 */
export const ensureScrolithaPlatformUser = async (): Promise<ScrolithaPlatformUser> => {
  if (identityCache && identityCache.expiresAt > Date.now()) {
    return identityCache.value;
  }

  const existing = await prisma.user.findFirst({
    where: {
      OR: [
        { username: { equals: SCROLITHA_PLATFORM_USERNAME, mode: 'insensitive' } },
        { email: SCROLITHA_PLATFORM_EMAIL }
      ]
    },
    select: {
      id: true,
      username: true,
      name: true,
      avatar: true,
      isVerified: true,
      isActive: true,
      role: true,
      email: true
    }
  });

  if (existing) {
    // Keep identity fields authoritative without blocking if concurrent updates fail.
    try {
      const patched = await prisma.user.update({
        where: { id: existing.id },
        data: {
          username: SCROLITHA_PLATFORM_USERNAME,
          name: SCROLITHA_PLATFORM_DISPLAY_NAME,
          isVerified: true,
          // Keep active so FK/comment author relations work; login is blocked by missing password + email domain.
          isActive: true
        },
        select: {
          id: true,
          username: true,
          name: true,
          avatar: true,
          isVerified: true,
          isActive: true,
          role: true
        }
      });
      const identity = toPublicIdentity(patched);
      identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
      return identity;
    } catch {
      const identity = toPublicIdentity(existing);
      identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
      return identity;
    }
  }

  try {
    const created = await prisma.user.create({
      data: {
        email: SCROLITHA_PLATFORM_EMAIL,
        username: SCROLITHA_PLATFORM_USERNAME,
        name: SCROLITHA_PLATFORM_DISPLAY_NAME,
        passwordHash: null,
        isVerified: true,
        isActive: true,
        role: 'USER',
        profile: {
          create: {
            title: 'Official Scrolith AI assistant',
            bio: 'Scrolitha helps users understand posts, claims, and platform context. Responses are AI-generated and may be incomplete. Never presents unsupported statements as verified fact.'
          }
        }
      },
      select: {
        id: true,
        username: true,
        name: true,
        avatar: true,
        isVerified: true,
        isActive: true,
        role: true
      }
    });

    const identity = toPublicIdentity(created);
    identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
    return identity;
  } catch (error: any) {
    // Concurrent create race (unique username/email) — re-read winner.
    const code = String(error?.code || '');
    if (code === 'P2002' || /unique/i.test(String(error?.message || ''))) {
      const raced = await prisma.user.findFirst({
        where: {
          OR: [
            { username: { equals: SCROLITHA_PLATFORM_USERNAME, mode: 'insensitive' } },
            { email: SCROLITHA_PLATFORM_EMAIL }
          ]
        },
        select: {
          id: true,
          username: true,
          name: true,
          avatar: true,
          isVerified: true,
          isActive: true,
          role: true
        }
      });
      if (raced) {
        const identity = toPublicIdentity(raced);
        identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
        return identity;
      }
    }
    throw error;
  }
};

export const getScrolithaPlatformUserId = async (): Promise<string> => {
  const identity = await ensureScrolithaPlatformUser();
  return identity.id;
};

export const isScrolithaPlatformUserId = async (userId: string | null | undefined): Promise<boolean> => {
  const id = String(userId || '').trim();
  if (!id) return false;
  const platformId = await getScrolithaPlatformUserId();
  return id === platformId;
};

/** Phase 20.2.4: accept @Scrolitha, @scrolitha, and @AI aliases. */
export const isScrolithaUsername = (username: string | null | undefined): boolean => {
  const normalized = String(username || '')
    .trim()
    .toLowerCase()
    .replace(/^@/, '');
  return (
    normalized === SCROLITHA_PLATFORM_USERNAME ||
    normalized === 'ai' ||
    normalized === 'scrolitha_ai' ||
    normalized === 'scrolitha-bot'
  );
};

/** Usernames that normal accounts cannot claim. */
export const isReservedScrolithaUsername = (username: string | null | undefined): boolean => {
  const normalized = String(username || '')
    .trim()
    .toLowerCase()
    .replace(/^@/, '');
  return (
    normalized === SCROLITHA_PLATFORM_USERNAME ||
    normalized === 'ai' ||
    normalized === 'scrolitha_ai' ||
    normalized === 'scrolitha-bot' ||
    normalized === 'official_scrolitha'
  );
};

export const clearScrolithaPlatformIdentityCache = () => {
  identityCache = null;
};
