import prisma from '../../utils/prismaClient';

/**
 * Stable platform identity for Scrolitha AI replies in comment threads.
 * Uses existing User model only — no schema migration.
 */
export const SCROLITHA_PLATFORM_USERNAME = 'scrolitha';
export const SCROLITHA_PLATFORM_DISPLAY_NAME = 'Scrolitha';
export const SCROLITHA_PLATFORM_EMAIL = 'scrolitha@system.scrolith.internal';
export const SCROLITHA_SYSTEM_LABEL = 'AI assistant';
export const SCROLITHA_DISCLOSURE =
  'This response was generated by Scrolitha, Scrolith’s AI assistant. Verify important claims independently.';

/**
 * Phase 20.7.9 — Canonical official identity assets (public file-content URLs, audited HTTP 200 / image/png).
 * All Scrolitha surfaces must prefer these over hard-coded icon fallbacks.
 */
export const SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL =
  process.env.SCROLITHA_PROFILE_PHOTO_URL ||
  'https://api.scrolith.com/api/files/content/edd2e7e7-1b32-4edd-9209-6e87fe80ea45';
export const SCROLITHA_OFFICIAL_COVER_PHOTO_URL =
  process.env.SCROLITHA_COVER_PHOTO_URL ||
  'https://api.scrolith.com/api/files/content/a163c581-9ca1-4561-a41f-0540c7fb9214';
export const SCROLITHA_OFFICIAL_PROFILE_PHOTO_FILE_ID = 'edd2e7e7-1b32-4edd-9209-6e87fe80ea45';
export const SCROLITHA_OFFICIAL_COVER_PHOTO_FILE_ID = 'a163c581-9ca1-4561-a41f-0540c7fb9214';
/** Cache-bust suffix for clients when official art changes. */
export const SCROLITHA_ASSET_VERSION = process.env.SCROLITHA_ASSET_VERSION || 'p2079';

export type ScrolithaPlatformUser = {
  id: string;
  username: string;
  name: string;
  avatar: string | null;
  coverPhotoUrl?: string | null;
  profilePhotoFileId?: string | null;
  coverPhotoFileId?: string | null;
  assetVersion?: string;
  isVerified: boolean;
  isActive: boolean;
  role: string;
  isScrolitha: true;
  systemLabel: string;
  disclosure: string;
  identityType?: 'system_ai';
  official?: true;
};

export const withScrolithaAssetVersion = (url: string | null | undefined): string => {
  const base = String(url || SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL).trim();
  if (!base) return SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL;
  const sep = base.includes('?') ? '&' : '?';
  if (/[?&]v=/.test(base)) return base;
  return `${base}${sep}v=${encodeURIComponent(SCROLITHA_ASSET_VERSION)}`;
};

const IDENTITY_CACHE_TTL_MS = 5 * 60_000;
let identityCache: { expiresAt: number; value: ScrolithaPlatformUser } | null = null;

const toPublicIdentity = (user: {
  id: string;
  username: string | null;
  name: string | null;
  avatar: string | null;
  profilePhotoFileId?: string | null;
  isVerified: boolean;
  isActive: boolean;
  role: string;
}): ScrolithaPlatformUser => {
  const managedAvatar = String(user.avatar || '').trim();
  const managedFileId = String(user.profilePhotoFileId || '').trim();
  // Prefer admin-managed photo when set; fall back to canonical official assets.
  const avatar =
    managedAvatar ||
    (managedFileId
      ? `https://api.scrolith.com/api/files/content/${encodeURIComponent(managedFileId)}`
      : SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL);
  return {
    id: user.id,
    username: String(user.username || SCROLITHA_PLATFORM_USERNAME).toLowerCase(),
    name: user.name || SCROLITHA_PLATFORM_DISPLAY_NAME,
    avatar: withScrolithaAssetVersion(avatar),
    coverPhotoUrl: withScrolithaAssetVersion(SCROLITHA_OFFICIAL_COVER_PHOTO_URL),
    profilePhotoFileId: managedFileId || SCROLITHA_OFFICIAL_PROFILE_PHOTO_FILE_ID,
    coverPhotoFileId: SCROLITHA_OFFICIAL_COVER_PHOTO_FILE_ID,
    assetVersion: SCROLITHA_ASSET_VERSION,
    isVerified: user.isVerified !== false,
    isActive: user.isActive !== false,
    role: String(user.role || 'USER'),
    isScrolitha: true,
    systemLabel: SCROLITHA_SYSTEM_LABEL,
    disclosure: SCROLITHA_DISCLOSURE,
    identityType: 'system_ai',
    official: true
  };
};

/** Clear in-memory identity cache after admin updates Scrolitha profile fields. */
export const clearScrolithaPlatformIdentityCache = () => {
  identityCache = null;
};

/**
 * Find or create the reserved Scrolitha platform user.
 * Protected identity: fixed username, verified badge, inactive for normal login paths.
 */
export const ensureScrolithaPlatformUser = async (): Promise<ScrolithaPlatformUser> => {
  if (identityCache && identityCache.expiresAt > Date.now()) {
    return identityCache.value;
  }

  const existing = await prisma.user.findFirst({
    where: {
      OR: [
        { username: { equals: SCROLITHA_PLATFORM_USERNAME, mode: 'insensitive' } },
        { email: SCROLITHA_PLATFORM_EMAIL }
      ]
    },
    select: {
      id: true,
      username: true,
      name: true,
      avatar: true,
      profilePhotoFileId: true,
      isVerified: true,
      isActive: true,
      role: true,
      email: true
    }
  });

  if (existing) {
    // Soft-heal only missing/broken identity fields.
    // Admin may manage display name, email, avatar, and verification — never overwrite those.
    try {
      const heal: Record<string, any> = {};
      if (String(existing.username || '').toLowerCase() !== SCROLITHA_PLATFORM_USERNAME) {
        heal.username = SCROLITHA_PLATFORM_USERNAME;
      }
      if (!String(existing.name || '').trim()) {
        heal.name = SCROLITHA_PLATFORM_DISPLAY_NAME;
      }
      if (!String(existing.avatar || '').trim()) {
        heal.avatar = SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL;
      }
      // Keep active so FK/comment author relations work; login is blocked by missing password + email domain.
      if (existing.isActive === false) {
        heal.isActive = true;
      }

      const patched =
        Object.keys(heal).length > 0
          ? await prisma.user.update({
              where: { id: existing.id },
              data: heal,
              select: {
                id: true,
                username: true,
                name: true,
                avatar: true,
                profilePhotoFileId: true,
                isVerified: true,
                isActive: true,
                role: true
              }
            })
          : await prisma.user.findUnique({
              where: { id: existing.id },
              select: {
                id: true,
                username: true,
                name: true,
                avatar: true,
                profilePhotoFileId: true,
                isVerified: true,
                isActive: true,
                role: true
              }
            });

      if (!patched) {
        const identity = toPublicIdentity(existing);
        identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
        return identity;
      }

      const identity = toPublicIdentity(patched);
      identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
      return identity;
    } catch {
      const identity = toPublicIdentity(existing);
      identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
      return identity;
    }
  }

  try {
    const created = await prisma.user.create({
      data: {
        email: SCROLITHA_PLATFORM_EMAIL,
        username: SCROLITHA_PLATFORM_USERNAME,
        name: SCROLITHA_PLATFORM_DISPLAY_NAME,
        avatar: SCROLITHA_OFFICIAL_PROFILE_PHOTO_URL,
        passwordHash: null,
        isVerified: true,
        isActive: true,
        role: 'USER',
        profile: {
          create: {
            title: 'Official Scrolith AI assistant',
            bio: 'Scrolitha helps users understand posts, claims, and platform context. Responses are AI-generated and may be incomplete. Never presents unsupported statements as verified fact.'
          }
        }
      },
      select: {
        id: true,
        username: true,
        name: true,
        avatar: true,
        isVerified: true,
        isActive: true,
        role: true
      }
    });

    const identity = toPublicIdentity(created);
    identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
    return identity;
  } catch (error: any) {
    // Concurrent create race (unique username/email) — re-read winner.
    const code = String(error?.code || '');
    if (code === 'P2002' || /unique/i.test(String(error?.message || ''))) {
      const raced = await prisma.user.findFirst({
        where: {
          OR: [
            { username: { equals: SCROLITHA_PLATFORM_USERNAME, mode: 'insensitive' } },
            { email: SCROLITHA_PLATFORM_EMAIL }
          ]
        },
        select: {
          id: true,
          username: true,
          name: true,
          avatar: true,
          isVerified: true,
          isActive: true,
          role: true
        }
      });
      if (raced) {
        const identity = toPublicIdentity(raced);
        identityCache = { expiresAt: Date.now() + IDENTITY_CACHE_TTL_MS, value: identity };
        return identity;
      }
    }
    throw error;
  }
};

export const getScrolithaPlatformUserId = async (): Promise<string> => {
  const identity = await ensureScrolithaPlatformUser();
  return identity.id;
};

export const isScrolithaPlatformUserId = async (userId: string | null | undefined): Promise<boolean> => {
  const id = String(userId || '').trim();
  if (!id) return false;
  const platformId = await getScrolithaPlatformUserId();
  return id === platformId;
};

/** Phase 20.2.4: accept @Scrolitha, @scrolitha, and @AI aliases. */
export const isScrolithaUsername = (username: string | null | undefined): boolean => {
  const normalized = String(username || '')
    .trim()
    .toLowerCase()
    .replace(/^@/, '');
  return (
    normalized === SCROLITHA_PLATFORM_USERNAME ||
    normalized === 'ai' ||
    normalized === 'scrolitha_ai' ||
    normalized === 'scrolitha-bot'
  );
};

/** Usernames that normal accounts cannot claim. */
export const isReservedScrolithaUsername = (username: string | null | undefined): boolean => {
  const normalized = String(username || '')
    .trim()
    .toLowerCase()
    .replace(/^@/, '');
  return (
    normalized === SCROLITHA_PLATFORM_USERNAME ||
    normalized === 'ai' ||
    normalized === 'scrolitha_ai' ||
    normalized === 'scrolitha-bot' ||
    normalized === 'official_scrolitha'
  );
};
